enum ErrorCode {
  CREATE_USER_ERROR = "CREATE_USER_ERROR",
  CREATE_COURSE_ERROR = "CREATE_USER_ERROR",
  GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR",
  GET_ALL_COURSES_ERROR = "GET_ALL_COURSES_ERROR",
}

export default ErrorCode;
